using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum UnitType {
	EMPTY,
	INNERWALL_LEFT,
	INNERWALL_RIGHT,
	INNERWALL_DOWN,
	INNERWALL_UP,
	INNERWALL_CORNER_TL,
	INNERWALL_CORNER_TR,
	INNERWALL_CORNER_DL,
	INNERWALL_CORNER_DR,
	OUTERWALL_LEFT,
	OUTERWALL_RIGHT,
	OUTERWALL_DOWN,
	OUTERWALL_UP,
	OUTERWALL_CORNER_TL_I,
	OUTERWALL_CORNER_TR_I,
	OUTERWALL_CORNER_DL_I,
	OUTERWALL_CORNER_DR_I,
	OUTERWALL_CORNER_TL_O,
	OUTERWALL_CORNER_TR_O,
	OUTERWALL_CORNER_DL_O,
	OUTERWALL_CORNER_DR_O,
	GARDEN,
	DOOR,
	WINDOW,
	INNER_GROUND,
	INNER_WALLS,
	OUTER_WALLS
}
